### ISSUE TITLE
Issue with the latest version of Chat enhancement

### ISSUE THREAD

**Issue by DarKDinDoN** [flamewave000/dragonflagon-fvtt#45]
Hello,

For some reason my world doesn't get the newest features of your package.
Trying in a new world, I have access to the /log command but not in a world that already had the package installed & activated.

- Package is up to date 
- FVTT 0.7.9
- 5E 1.2.4
- Only this package, chat command & tidy settings activated (others installed, but deactivated for the purposes of this test).

EDIT: to be clear. Both worlds are hosted on the same FVTT instance. Meaning that both are using the same version of the module. Could it mean some kind of world data not up to date on the world? Or some migration issue?

**Comment by flamewave000** [comment]
Hmm that sounds very odd. There's no migration to be done since the features don't interact with each other in any way. Could you check the Console to see if there are any errors?

**Comment by DarKDinDoN** [comment]
Yes, I have this error
![image](https://user-images.githubusercontent.com/1687854/107979627-2f6c5e80-6fbf-11eb-8f91-70502fda1fae.png)

**Comment by flamewave000** [comment]
Perfect, I can work with that 👍

**Comment by flamewave000** [comment]
This should be fixed in v1.0.1 now, you can pull it and let me know if you have any other issues. Thanks!

**Comment by DarKDinDoN** [comment]
@flamewave000 installed 1.0.1. Still have this issue.
Same error
![image](https://user-images.githubusercontent.com/1687854/107986304-17e7a280-6fcc-11eb-8209-910bd14237ff.png)

**Comment by DarKDinDoN** [comment]
@flamewave000 Found the issue.
For some reason, I had to deactivate the log setting in the module configuration and reactivate it again for the rest of the settings to appear.

**Comment by DarKDinDoN** [comment]
@flamewave000 Found the bug!
If this setting is checked the rest of the log configuration is not available. Seems that this module is not recognizing me as the GM!
![image](https://user-images.githubusercontent.com/1687854/108045323-a0edf080-7043-11eb-8dbf-5f1d2d1e3b07.png)

**Comment by flamewave000** [comment]
Ok, thanks for the extra info. I was able to reproduce the issue and basically the AdventureLog was crashing and causing the rest to fail. It will be fixed in the next release.
